### ISSUE TITLE
Sveltekit-preload-data works when hovering a link with a query, but breaks page rendering and HMR if it is clicked before the prefetching is done

### ISSUE THREAD

**Issue by AristideBH** [HoudiniGraphql/houdini#742] opened 2022-12-05 14:52 UTC
### Describe the bug

Trying to use Houdini on a new Sveltekit project, i get a weird behaviour : 
I've setup my query inside a route, the recommended way in the doc (via `+page.gql`), 
but also tried with inline query in `+page.svelte.`

When I navigate to the route, the data loads as expected and I get not error.
But when I come from another route (eg; /), using a link, no data is loaded, breaks the page rendering and HMR.
I get the following errors : 
![image](https://user-images.githubusercontent.com/11951633/205659538-1b5a6747-15b9-4a1c-96ff-a72445f4c4fc.png)

Upon further inspection, it's seems linked to the Sveltekit prefecthing on hover,
setup in the `body` tag (with [data-sveltekit-preload-data="hover"](https://kit.svelte.dev/docs/link-options#data-sveltekit-preload-data)) in `app.html` :
- Clicking the link right after the mouse has hoverred it (therefore no time to prefetch), 
the page breaks with the aforementioned errors
- Clicking the link after having the mouse hoverred it for a few second, allowing for prefetching, give the expected result (page loads with data)
(in the network tab, we can see the request is successfully made on hover, and response is received)
- Disabling the prefetch on hover on the `body `tag give the error, no matter how much time I hover on the link (no request on hover in network tab)

I cannot expect users to hold their cursor a few seconds on the link before actually clicking it, waiting the prefecthing to be fully executed to render the page. I kinda beats the advantages of prefetching.
Also, disabling the prefetching altogether (or setting it to "tap") doesn't help at all, as the query seems to notb executed when navigating to the page.

I wasn't able to put a Stackbitz example up, but I made a [repo ](https://github.com/AristideBH/sk-houdini-test) you can clone to quickly take a look a this config

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

1. Create a new Sveltekit project using `npm create svelte@latest houdini-test`, as a skeleton project, doesn't matter if JS or TS
2. Install dependencies `npm i`
3. Install and initialize Houdini `npm install --save-dev houdini` and `npx houdini init`
  using [https://graphqlzero.almansi.me/api](https://graphqlzero.almansi.me/api) as a mock api
4. Install Houdini dependencies `npm i`
5. Create a test route with a graphql query (either with `+page.gql` or inline in `+page.svelte`)
6. Add a `+layout.svelte` with link to the newly created route
7. Run the dev server `npm run dev`
8. Open devtools/network tab
9. Hover a few seconds on the route with the query : the request is sent and response received > the page and data load
10. Refresh to homepage, click on the link without waiting on hover : the page breaks and the query is not run

### Reproduction

https://github.com/AristideBH/sk-houdini-test

**Comment by AlecAivazis** [comment] 2022-12-05 16:54
Hey @AristideBH - sorry to hear you are running into this and thanks for taking the time to put that reproduction together.

Looking at your example, I think the problem is that you aren't checking if the query is still loading when you render. If you change your `+page.svelte` file to this, it should work:

```
{#if !$GetPosts.isFetching}
<div>
	{#each $GetPosts.data.posts.data as post}
		<article>
			{post.title}
		</article>
	{/each}
</div>
{/if}
```

**Comment by AristideBH** [comment] 2022-12-05 22:33
Thanks @AlecAivazis for your quick answer !
It indeed worked flawlessly, and I can apply that as a fix for my queried data.

However, is it expected behaviour ?
I could not find this recommandation in the docs

There may be some usages, features or obstacle I am missing doing so, but it seems a bit of boilerplate code to make data accessible on page change

Thanks again, I'd gladly be advised about this

**Comment by AlecAivazis** [comment] 2022-12-05 22:39
At the moment, any query needs to have its fetching state checked explicitly. I have a few ideas for ways to clean this up (see #662 ) but until then, checking `isFetching` is the best way

**Comment by AlecAivazis** [comment] 2022-12-06 05:07
I'm going to close this to keep things tiday. Feel free to let me know if something comes up and I can reopen if necessary

**Closed by AlecAivazis** 2022-12-06 05:08 UTC
