### ISSUE TITLE
Schema is not pulled when using "--headers"

### ISSUE THREAD

**Issue by sdekna** [HoudiniGraphql/houdini#606] opened 2022-10-14 14:50 UTC
### Describe the bug

I have a Hasura graphql server that requires headers `x-hasura-admin-secret="$secret key"`... However, when I try to initialize houdini with the `--headers / -h` necessary argument, it does not pull any schema. Tried headers with other clients and it works.
My command is like this: `npx houdini init --headers x-hasura-admin-secret="$secret key"`

The initialization process continues normally with no errors, but nothing is pulled... If I try `npx houdini pull-schema` it gives no error but doesn't pull the schema still`.

Any ideas?

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

1- start new project and install dependencies.
2- npx npx houdini init --headers x-hasura-admin-secret="$secret key"

**Comment by AlecAivazis** [comment] 2022-10-14 19:46
Thanks for reporting this @sdekna! I'll work on a fix this weekend

**Comment by AlecAivazis** [comment] 2022-10-16 21:20
So i'm unable to reproduce this with #593 merged. I can't think of what exactly could have changed in that effort but it's very possible this isn't a problem any more. Mind trying again once `0.17.0` has been released? Shouldn't be too much longer now

**Comment by sdekna** [comment] 2022-10-16 22:15
Sure thing! :smile:

**Comment by sdekna** [comment] 2022-10-16 22:32
Just to be sure I am not doing something wrong, this is how I am trying to pull the schema:
- Tried during initialization with: `npx houdini init -h x-hasura-admin-secret="key"`
- Tried after with: `npx houdini pull-schema -h x-hasura-admin-secret="key"`

Both give no errors but pull no schema nor types.

**Comment by AlecAivazis** [comment] 2022-10-17 00:51
yea that should work! I was seeing `{"x-hasura-admin-secret": "key"}` when I logged the headers being passed to fetch. I didn't check if I was seeing the same thing in the original code but we can debug what's going on if its still broken in a few days

**Comment by sdekna** [comment] 2022-10-17 12:44
excellent. Thanks for the support 🙏😁

**Comment by AlecAivazis** [comment] 2022-10-21 20:48
Okay, `0.17.0` has been released - mind giving it a try @sdekna ?

**Comment by sdekna** [comment] 2022-10-21 23:46
Now its pulling schema perfectly :pray: 
Works well with queries, however, for subscriptions when I use `import { graphql, subscription } from '$houdini'`, it doesn't import it saying `'"$houdini"' has no exported member named 'subscription'`

**Comment by AlecAivazis** [comment] 2022-10-22 01:30
That's because it was removed in 0.16.0. Now you can just use the graphql tag directly. I'm out to dinner so I can't grab a link to the docs but you should be able to see an example to copy there

**Closed** 2022-10-22 01:30 UTC
Labels: Bug

**Comment by AlecAivazis** [comment] 2022-10-22 03:42
Just got back. Here is the link to the subscription docs: https://www.houdinigraphql.com/api/subscription

**Comment by sdekna** [comment] 2022-10-22 11:17
amazing! everything looks good now... many thanks for the support man! :pray:
