### ISSUE TITLE
return value of fetch and mutate methods does not correspond to network response

### ISSUE THREAD

**Issue by TheophileMot** [HoudiniGraphql/houdini#1108] opened 2023-06-17 19:12 UTC
### Describe the bug

I have a sequence of pages that create an object then update it with more information. When it updates, the Houdini value is not the same as what I see in the Network panel in Chrome dev tools.

The actual object schema is complex, but to keep it simple, let's say it looks like `{id: UUID!, title: string!, places: [Place]}`. The `places` field starts out empty and will be populated by the second upsert.

```
// FirstComponent.svelte

await new UpsertMyObjectStore().mutate({ title: 'my object' });
// { id: 'abcd-0123', title: 'my object', places: null }

// Load next page
document.location.href = anotherUrl;
```

Then:
```
// SecondComponent.svelte

const initialObj = await new GetMyObjectStore().query({ id: 'abcd-0123' }).data;
// { id: 'abcd-0123', title: 'my object', places: null }

const newPlaces = [ ... ];

const response = await new UpsertMyObjectStore().mutate({
  title: 'a better title',
  places: newPlaces
}).data;

const updatedObj = await new GetMyObjectStore().query({ id: 'abcd-0123' }).data; 
```

The Network panel shows that the server returns an object with the new title and array of places. I can see in the database that the operations were successful. Houdini, however, gives a null `places` field instead of the correct array.

```
console.log(response);
// { id: 'abcd-0123', title: 'a better title', places: null }  <--- `title` is right, `places` is wrong

console.log(updatedObj);
// { id: 'abcd-0123', title: 'a better title', places: null }  <--- `title` is right, `places` is wrong
```

---

I've spent hours trying everything I can think of—making sure to use `NetworkOnly`, manually clearing caches, setting timeouts between API calls, etc.—but I feel like I'm missing something. Is it normal or even possible that the return value is different from the network response?

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

I can't share much because of strict IP policies, but here's a screenshot showing the network traffic vs. what Houdini reports:

<img width="796" alt="image" src="https://github.com/HoudiniGraphql/houdini/assets/34871447/0cd6b179-1878-41d8-8630-340ba0ba0d9e">

**Comment by TheophileMot** [comment] 2023-06-18 17:14
I should mention that when I refresh the page, the `GetMyObjectStore` query *does* return the correct data, which is why it seems to be a caching issue (even though the store says that its source is "Network").

**Comment by AlecAivazis** [comment] 2023-06-18 20:05
Thank you for the detailed report @TheophileMot! I'm sorry to hear you are running into this. Unforunately, due to the limited inforimation that you are able to share, it will be very hard to debug what exactly is going on. 

Could you try to use the [e2e tests  in this repo](https://github.com/HoudiniGraphql/houdini/tree/main/e2e/kit) to create a reproduction? That would be incredibly helpful

**Comment by TheophileMot** [comment] 2023-06-23 14:27
@AlecAivazis Thank you for directing me to the e2e tests. I realise that it's not really feasible to look into the issue without being able to replicate it; if ever I get the time, I'll see if I can make a test.

For posterity, I managed to circumvent the issue for now by writing a client plugin. The `afterNetwork` step has the correct data, while the `end` step is incorrect; therefore, I put the data in `afterNetwork` into `ctx.stuff`, and use that in the `end` step instead of whatever Houdini thinks it should be.

**Comment by AlecAivazis** [comment] 2023-06-28 01:00
Okay good to hear you fixed this. I'm going to close the issue until we have something more concrete to address

**Closed by AlecAivazis** 2023-06-28 01:00 UTC
