### ISSUE TITLE
`_insert` only works on the first loaded list

### ISSUE THREAD

**Issue by alexlafroscia** [HoudiniGraphql/houdini#314] opened 2022-06-07 16:07 UTC
After going down a rabbit hole with #308 in hopes of resolving the problem myself, it turns out that adding the `@append` (or any other list manipulation clues) to the query didn't solve my problem. Here's a re-cap from that issue's description:

---

I have a query like this in my application, which is displayed on a route like `/list/:primaryKey`:

```gql
query ListPage($primaryKey: Int!) {
  list(primaryKey: $primaryKey) {
    id # `ID` for the purposes of implementing the `Node` interface
    primaryKey # Actual `id` in the database; queries use this data instead

    items @list(name: "ListPageItems") {
      id
      content
    }
}
```

Within that page, I have a button to create a new item within that list:

```gql
mutation AddItemToList($listPrimaryKey: Int!) {
  createItemInList(listPrimaryKey: $listPrimaryKey) {
    ...ListPageItems_insert
  }
}
```

This works fine on the first list page navigated to (say, `/list/1`) but breaks if I perform a navigation to another list (like `/list/2`) without fully reloading the page. If I stay on the initial list, the list is inserted into automatically. If I navigate to the second list and try to perform the mutation, the operation is successful but the item just doesn't appear in _either_ of the lists. Refreshing `/list/2` then shows the item correctly, since it's loaded anew from the API.

---

Since this issue is kind of hard to discuss in the abstract, I created a demonstration repo that you can find here:

https://github.com/alexlafroscia/demo-houdini-bug-with-list-insertion

To reproduce the issue, you can perform the following steps:

1. Run `yarn dev` and open the homepage for the site
2. Click on the first list item
3. Use the `input` to add an item to the list. It should appear automatically on the page, thanks to an `_insert` fragment. _Do not refresh the page!_
4. Use the link at the top to navigate back to the homepage
5. Click on the second list item
6. Use the `input` to add an item to the list

This will _not_ result in the item becoming visible on the page.

To simplify this loop, I wrote a Playwright test that also does these steps. You can run `yarn test` to execute it. The test should fail based on the text `Second Item` that _should_ be on the page, but is not.

I have attempt to resolve this issue by using the `@append` and `@parentID` directives, neither of which help. They actually both make the problem _worse_, breaking the successful dynamic insertion on the first page to be loaded. With either of those directives in use, _neither_ list can be dynamically inserted into.

**Comment by alexlafroscia** [comment] 2022-06-07 16:27
It seems like my Playwright test isn't actually correct; I'm working on fixing it so that it correctly demonstrates the bug.

The manual steps should show the issue, though!

**Comment by alexlafroscia** [comment] 2022-06-07 17:17
Okay, the test in the repo for the reproduction should actually represent the bug now!

Here's also the screen recording from Playwright. The parts that work happen _really_ quickly, so I found it easiest to manually scrub through the video at a slower speed.

https://user-images.githubusercontent.com/1645881/172443645-757badba-8578-4d48-8d91-09ee1acfeb9b.mp4

**Comment by AlecAivazis** [comment] 2022-06-09 08:53
Okay, I found some time to dig into this and I have a pretty good idea what's causing it. I'll try to get something out as soon as I can find the time. shouldn't be more than a few days. 

thanks again for putting together the reproduction. It was super helpful

**Comment by alexlafroscia** [comment] 2022-06-09 13:24
That's great to hear! No problem at all on the reproduction; I don't do a lot of OSS maintenance these days but did for many years, and I know a solid reproduction is the difference between getting something fixed and having the error sit around a while. Thank _you_ for digging into it!

**Comment by AlecAivazis** [comment] 2022-06-09 21:03
Okay, I'm pretty sure I have a fix for this. 

Unfortunately, I had to change the way that `@parentID` works but the previous behavior wasn't correct since it could not support the situation you ran into. This is one of those annoying situations that technically has a break in the API even though it is really a bug fix. 

I'd prefer to include this in the `0.15.0` release which is coming soon. That does mean you will have to install a prerelease version with the fix until #291 is merged and tested. I think if I release the fix before the store api work you should be able to freeze to a version of `0.15.0` that does not include a large refactoring before its been thoroughly tested. Does that sound okay to you?

**Closed** 2022-06-10 06:20 UTC

**Comment by AlecAivazis** [comment] 2022-06-10 06:27
This should now be fixed in `houdini@next`. The exact version is `v0.15.0-next.0` in case you want to freeze it

**Comment by alexlafroscia** [comment] 2022-06-16 18:00
Awesome, thanks @AlecAivazis! I haven't had a chance to kick the tires on this yet, but will do so soon and let you know how it goes!
