### ISSUE TITLE
Houdini + SvelteKit prerendering without SSR tries to load missing `__data.json`

### ISSUE THREAD

**Issue by ascclemens** [HoudiniGraphql/houdini#739] opened 2022-12-03 05:18 UTC
### Describe the bug

When setting up a SvelteKit project with Houdini, if SSR is disabled and prerendering enabled, attempting to access the site will query for `__data.json` files that do not exist, causing 500 errors.

Running `yarn build` once, removing the Vite plugin, then running `yarn build` again mitigates the issue, but this isn't tenable for CI.

Let me know if I'm missing something obvious that's my fault!

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. Create a new SvelteKit + TS project (`yarn create svelte test-project`)
2. Install dependencies (`yarn`)
3. Add Houdini (`yarn add -D houdini; yarn run houdini init`, add Vite plugin to config`)
4. Build (`yarn build`)
5. Run preview (`yarn run preview`)
6. Try to access index

I made a repository that can reproduce this issue. Just clone it, `yarn; yarn build; yarn run preview`.

### Reproduction

https://github.com/ascclemens/houdini-no-ssr-issue

**Comment by AlecAivazis** [comment] 2022-12-05 01:51
Huh,  that's very strange. Thanks for reporting this. 

It'll probably be a little bit before I have some time to dig into this. If you have the time to figure this out, I'd gladly offer any help you need here or on discord.

**Comment by AlecAivazis** [comment] 2022-12-20 22:34
Okay, i pulled down the reproduction. Thanks for putting that together - i was able to see the issue.

The issue did go away when I updated kit to the latest version i don't think this is a problem any more. I'm going to close this issue to keep things tidy but feel free to let me know if you're still running into this and I can reopen it

**Comment by ascclemens** [comment] 2022-12-21 01:36
I can verify that this still happens. I have updated the reproduction repository.

**Comment by AlecAivazis** [comment] 2022-12-21 07:26
Ah yea I see that too. I'll take a look and see what I can find

**Comment by AlecAivazis** [comment] 2022-12-21 09:01
Okay, as far as I can tell, I think this issue is related to a combination of these two issues: https://github.com/sveltejs/kit/issues/7967 and https://github.com/sveltejs/kit/issues/7637. Basically, the vite plugin causes a `.server.js` file to be created which understandably confuses kit during prerendering.

I have some ideas of things to try but it might take me a few days to find the time to dedicate to it since family is over for the holidays. thanks for being patient!

**Comment by AlecAivazis** [comment] 2022-12-22 01:48
Okay so once #786 gets merged, you'll be able to set `static` to `true` in your `houdini-svelte` config object to prevent the session infrastructure which was causing the request to `__data` to be sent.

**Closed** 2022-12-23 17:34 UTC
Labels: Bug

**Comment by AlecAivazis** [comment] 2022-12-23 18:50
The update should now be a part of `0.19.2`

**Comment by ascclemens** [comment] 2022-12-23 19:23
Can confirm it's fixed both in my minimal repro and in my original prod use-case, once `static: true` has been added to the Houdini config. Thank you so much!

**Comment by AlecAivazis** [comment] 2022-12-23 19:29
Fantastic! Thanks for confirming so quickly ❤️

**Comment by lukaso** [comment] 2023-08-01 22:09
This is still happening to me. Might be for a different reason. But it's definitely because of Houdini.
