### ISSUE TITLE
@next.19: TypeError: import_module.createRequire is not a function 

### ISSUE THREAD

**Issue by neoel** [HoudiniGraphql/houdini#906] opened 2023-02-06 18:46 UTC
### Describe the bug

I'm getting this error in the console (running svelte-kit@1.5 with houdini & houdini-svelte @next.19

```
Module "module" has been externalized for browser compatibility. Cannot access "module.createRequire" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details. [client.js:1837:15](http://app.wolbodo/node_modules/.pnpm/@sveltejs+kit@1.5.0_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=f665b7cd)
TypeError: import_module.createRequire is not a function
    <anonymous> index.js:1
[manifest.js:18:41](http://app.wolbodo/.svelte-kit/generated/client/manifest.js)
    handleError http://app.wolbodo/.svelte-kit/generated/client/manifest.js:18
    handle_error http://app.wolbodo/node_modules/.pnpm/@sveltejs+kit@1.5.0_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=f665b7cd:1787
    _hydrate http://app.wolbodo/node_modules/.pnpm/@sveltejs+kit@1.5.0_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=f665b7cd:1724
    start http://app.wolbodo/node_modules/.pnpm/@sveltejs+kit@1.5.0_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/runtime/client/start.js:33
    <anonymous> http://app.wolbodo/m/dexter:470
Uncaught (in promise) TypeError: import_module.createRequire is not a function
    <anonymous> index.js:1
[index.js:1:87](http://app.wolbodo/node_modules/.pnpm/houdini@1.0.0-next.19/node_modules/houdini/build/lib-esm/index.js)
Uncaught (in promise) TypeError: import_module.createRequire is not a function
    <anonymous> index.js:1
```

that `index.js:1` file is in the houdini library and reads:
```
import { createRequire as conflict_free } from 'module'; const require = conflict_free(import.meta.url);
```

### Severity

annoyance

### Steps to Reproduce the Bug

Pushed my codebase to https://github.com/wolbodo/members/tree/svelte-kit%40v1
Unsure what I did wrong in my codebase.

**Comment by AlecAivazis** [comment] 2023-02-06 22:38
Oh wow. So after a lot of clicking around, I think the issue is the `import { path } from 'houdini' in `src/lib/Header/index.svelte` which was causing server-side files to be bundled into your client (resulting in the error). I think this is also what was happening to you earlier when you were running into https://github.com/HoudiniGraphql/houdini/issues/854

**Comment by AlecAivazis** [comment] 2023-02-08 04:07
closing this one too 👋

**Closed by AlecAivazis** 2023-02-08 04:07 UTC

**Comment by neoel** [comment] 2023-02-08 07:12
Oh wow. Thanks!
I wonder if we could add some checking on whether the import is happening on the server.
I'm unsure why I even added it, but then again there's many broken bits in the app in the refactoring stage.. 

Thanks a lot!
