### ISSUE TITLE
Request with GET/HEAD method cannot have body.

### ISSUE THREAD

**Issue by david-plugge** [HoudiniGraphql/houdini#374] opened 2022-07-06 09:19 UTC
When using the new <gql store>.fetch i get the error `Request with GET/HEAD method cannot have body.`

(sveltekit version 1.0.0-next.359)

_src/routes/index.svelte_
```ts
export const load: Load = async function (event) {
    // works
	await event.fetch('/test', {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json'
		},
		body: JSON.stringify({
			hello: 'World'
		})
	});

    // breaks
	await GQL_Artworks.fetch({ event });

    return {};
};
```

My houdini client looks like this
```ts
async function fetchQuery({ fetch, text = '', variables = {}, session }: RequestHandlerArgs) {
	const headers: HeadersInit = {
		'Content-Type': 'application/json',
		apikey: import.meta.env.VITE_PUBLIC_KEY
	};
	if (session?.accessToken) {
		headers['Authorization'] = `Bearer ${session.accessToken}`;
	}

	const result = await fetch(url, {
		method: 'POST',
		headers,
		body: JSON.stringify({
			query: text,
			variables
		})
	});

	return await result.json();
}
```

**Comment by jycouet** [comment] 2022-07-06 12:20
Strange, it looks like you are doing a 'GET' somewhere? 🤔

In your first part, you query this URL: `/test`. Your graphql endpoint is on '/test'?
In your second part, where did you set url? Can you try with exact same headers?

Might be also the sveltekit version 1.0.0-next.359 that has some breaking changes.

**Comment by jycouet** [comment] 2022-07-06 12:36
Ok, it's a `sveltekit version 1.0.0-next.359` issue.

Even your first part is not working, check logs, you will have the same message: `Request with GET/HEAD method cannot have body.`

I'm looking at what it could be. Thx for reporting 👍

**Comment by david-plugge** [comment] 2022-07-06 16:33
> Even your first part is not working

Somehow it was working, thast strange

**Comment by AlecAivazis** [comment] 2022-07-08 22:24
I believe this is now fixed - will try to confirm this weekend

**Comment by AlecAivazis** [comment] 2022-07-09 00:25
Just confirmed this is working on `@sveltejs/kit@1.0.0-next.367`

**Closed by AlecAivazis** 2022-07-09 00:25 UTC
Labels: Bug
