### ISSUE TITLE
Customize Node interface assumptions

### ISSUE THREAD

**Issue by Quart3z** [HoudiniGraphql/houdini#411] opened 2022-07-14 13:22 UTC
Hi first time here, just wanna ask about the issue I've faced when running ``houdini generate``. 
```
Your project defines a Node interface but it does not conform to the Global Identification Spec.

If you are trying to provide the Node interface and its field, they must look like the following:

interface Node {
        id: ID!
}

extend type Query {
        node(id: ID!): Node
}
```
For reference, I am using type of ``UUID`` as ``id`` for each of my query and custom ``nodeId`` for globally unique identifier, for example

```
type Address implements Node {
.
id: UUID!
.
nodeId: ID!
.
.
```

and this is the interface for ``Node``:
```
interface Node {
  nodeId: ID!
}
```

Sorry for the dumb question, am I missing something or Houdini requires NodeId strictly in the name of ``id``? Thanks in forward

**Comment by jycouet** [comment] 2022-07-14 13:53
👋 welcome, it's a good question that can help other.

Having the `interface Node` is the first part, do you have also the second part with the resolver?
Something like: 
```graphql
extend type Query {
  node(id: ID!): Node
}
```

I'm not sure about the UUID type as it's not part of the 5 default SCALAR provided by GraphQL. (Int, Float, String, Boolean, ID).

Do you have a public repo to play with this a bit?
If not, let me know and I will test something on my end.

**Comment by Quart3z** [comment] 2022-07-15 03:51
@jycouet @AlecAivazis thanks for the replies guys, much appreciate. I've solved the issue by modifying my own schema so it's now compatible with Houdini

**Comment by AlecAivazis** [comment] 2022-10-22 04:07
I'm going to close this as Won't Fix. I know it'll probably bother some people but at this point Node has pretty universal semantic meaning so unless there is an overwhelming desire to fix this, I don't think it's worth the effort

**Closed by AlecAivazis** 2022-10-22 04:07 UTC
Labels: Enhancement

**Comment by AlecAivazis** [comment] 2023-09-21 00:12
Just wanted to remind anyone running into this issue that in v3 hasura now supports the standard `id` field!!! 🥳

**Comment by KyleFontenot** [comment] 2024-02-02 19:36
I'd like to open this up for reconsideration. 
If the expected `Node` interface is `id`, instead of `nodeId`, that essentially means for automated schemas that use `nodeId` we have to manually edit the whole schema, and we can't use the watchSchema feature. 
In addition to changing `interface Node {}`, this also means that each table type cannot have a `id` column becuase they're duplicates. 
I think it's a very tall ask to expect everyone to not have a column named `id` in any database table, especially because renaming primary keys is a mess.

**Comment by jycouet** [comment] 2024-02-02 21:10
If I'm not mistaken, you can still do `defaultKeys` in `houdini.config.js`.
```js
/** @type {import('houdini').ConfigFile} */
export default {
  // ...
  defaultKeys: ['nodeId']
}
```

---

I don't know the solution of Hasura, but in postgraphile, I know that the id in db is exposed as idRow in GraphQL and id in GraphQL is the node id. Nice trick. ^^

**Comment by KyleFontenot** [comment] 2024-02-23 18:24
> If I'm not mistaken, you can still do `defaultKeys` in `houdini.config.js`.
> 
> ```js
> /** @type {import('houdini').ConfigFile} */
> export default {
>   // ...
>   defaultKeys: ['nodeId']
> }
> ```
> 
> I don't know the solution of Hasura, but in postgraphile, I know that the id in db is exposed as idRow in GraphQL and id in GraphQL is the node id. Nice trick. ^^

Sorry took a while to get back to this, but yes I can confirm that `defaultKeys` works beautifully 👍 Didn't know it existed until your comment. Can close, thank you
