### ISSUE TITLE
Most `houdini-svelte` dependencies should be peer dependencies

### ISSUE THREAD

**Issue by GauBen** [HoudiniGraphql/houdini#1342] opened 2024-08-21 10:29 UTC
### Describe the bug

Hey Magicians! I'm trying out Houdini to see if it suits my needs

I have observed that all its dependencies are declared as direct dependencies instead of [peer dependencies](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#peerdependencies):

https://github.com/HoudiniGraphql/houdini/blob/677e2d1431d689e9d67822c0ef14937d0893c391/packages/houdini-svelte/package.json#L31-L42

I believe this is a mistake as the user is supposed to install vite, svelte, sveltekit, ... themself as part of their project setup, and houdini-svelte supposed to pick up the same packages. With direct dependencies, houdini-svelte has its own copies of these packages, which can create weird bugs:

![image](https://github.com/user-attachments/assets/a3de9c6b-c701-4bed-b698-f712005fc389)

Thanks for your time

**Comment by jycouet** [comment] 2024-08-21 10:39
On `houdini-svelte` yes `svelte` should probably also be a `peer` and `houdini` as well.
For others, I don't think so, _might be wrong_.

> which can create weird bugs

You have an issue in mind ?

**Comment by GauBen** [comment] 2024-08-21 10:57
Digging further, houdini-svelte actually ships **gigantic** code bundles: https://pkg-size.dev/houdini-svelte

- https://unpkg.com/houdini-svelte@1.2.55/build/preprocess-esm/index.js
- https://unpkg.com/houdini-svelte@1.2.55/build/plugin-esm/index.js

These files contain the entirety of svelte, recast, fs-extra, node-fetch, several matching libraries and a lot more. Because of this, I have at least 3 versions of svelte in node_modules:

* One bundled directly in node_modules/houdini-svelte/build
* One in node_modules/houdini-svelte/node_modules
* One in node_modules/

> You have an issue in mind?

It happened to me a while ago that an eslint plugin was shipping its own version of eslint, and it broke with mysterious error messages when updating the main eslint.

**Comment by jycouet** [comment] 2024-08-21 12:22
> Digging further, houdini-svelte actually ships **gigantic** code bundles: https://pkg-size.dev/houdini-svelte
> 
> * https://unpkg.com/houdini-svelte@1.2.55/build/preprocess-esm/index.js
> * https://unpkg.com/houdini-svelte@1.2.55/build/plugin-esm/index.js

Yes, all this is for the build pipeline & co. The cool thing is that nothing goes to the client. 
As in your client code, you are importing stuff from `$houdini` 👍

> These files contain the entirety of svelte, recast, fs-extra, node-fetch, several matching libraries and a lot more. Because of this, I have at least 3 versions of svelte in node_modules:
> 
> * One bundled directly in node_modules/houdini-svelte/build
> * One in node_modules/houdini-svelte/node_modules
> * One in node_modules/

I would say that it's like this that node & npm & pnpm works...
You can do `npm ls --depth=2` (and play with the number...) and you will see that for your project to work, you need a lot of things ^^. And trust me, you don't want to manage the version of the 1000 libs used for you.

> As a rule of thumb, libraries that the user manages themself should be marked as peer dependencies. Here is what it looks like for svelte-kit:
> 
> https://github.com/sveltejs/kit/blob/761b8afd33f45e6b9cf0be1fb3933213d4542b49/packages/kit/package.json#L48-L52

Exactly, check the link you sent, SvelteKit has 3 peer deps for userland, and a few dep that you should not care about.
That's why, probably `houdini-svelte` should probably have `svelte` and `houdini` as peer, but that's it. (not even SvelteKit as `houdini-svelte` can work without SvelteKit, in a pure svelte project.)

**Comment by AlecAivazis** [comment] 2024-08-23 22:12
I'm going to close this since I think the core of the issue is caused by some slight confusion - houdini's dependencies do not actually impact the  final bundle size of our user's apps

**Closed by AlecAivazis** 2024-08-23 22:12 UTC
