### ISSUE TITLE
Allow make path not `$houdini`?

### ISSUE THREAD

**Issue by endigma** [HoudiniGraphql/houdini#412] opened 2022-07-14 21:35 UTC
Having a dollar sign amidst a sea of `.something` for hidden folders filled with codegen seems unnecessarily "look at me", perhaps this can be configurable?

I would much rather to be able to put this into `src/lib/gen/houdini` next to other codegen things

**Comment by AlecAivazis** [comment] 2022-07-15 00:26
Thanks for opening this @endigma! It's definitely on our list of things to do when we  have time. I'm going to close this issue since its a duplicate of #391. Feel free to join the conversation over there 👍

**Closed by AlecAivazis** 2022-07-15 00:26 UTC
