### ISSUE TITLE
pageInfo Not Reset When Navigating Back to Page

### ISSUE THREAD

**Issue by austins** [HoudiniGraphql/houdini#795] opened 2022-12-27 20:50 UTC
### Describe the bug

**Environment information:**
```
        "graphql": "^16.6.0",
        "houdini": "^0.19.3",
        "houdini-svelte": "^0.19.3",
        "@sveltejs/adapter-node": "^1.0.0",
        "@sveltejs/kit": "^1.0.1",
```

I have a page that uses cursor pagination.

`GetPublishedArticles.qgl`:
```
query GetPublishedArticles {
    articles(input: { status: [PUBLISHED] }, first: 9) @paginate {
        edges {
            node {
                id
                name
                slug
                body
                excerpt
                createdAt
            }
        }
    }
}
```

`+page.ts` (using the `_houdini_load` way since the query will used in multiple pages and there will be variables later on):
```ts
import { GetPublishedArticlesStore } from "$houdini";

export const _houdini_load = [GetPublishedArticlesStore];
```

`+page.svelte`:
```ts
<script lang="ts">
    import Articles from "$lib/components/Articles.svelte";
    import LoadingSpinner from "$lib/components/LoadingSpinner.svelte";
    import type { PageData } from "./$houdini";

    export let data: PageData;

    $: ({ GetPublishedArticles } = data);
</script>

{#if $GetPublishedArticles.isFetching}
    <LoadingSpinner />
{:else if $GetPublishedArticles.data?.articles?.edges && $GetPublishedArticles.data.articles.edges.length > 0}
    
    {console.log($GetPublishedArticles.pageInfo)}

    <Articles
        articles={$GetPublishedArticles.data.articles.edges}
        hasNextPage={$GetPublishedArticles.pageInfo.hasNextPage}
        loadNextPage={async () => await GetPublishedArticles.loadNextPage()}
    />
{:else}
    No articles found.
{/if}
```

This conditional could be cleaned up, but I'm just experimenting with Houdini for now.

The initial page load's `pageInfo`:
```ts
Object { hasPreviousPage: false, hasNextPage: true, startCursor: "MA==", endCursor: "OA==" }
```

loadNextPage() called once:
```ts
Object { hasPreviousPage: true, hasNextPage: false, startCursor: "OQ==", endCursor: "MTU=" }
```

**Observed behavior:**
If you navigate to another page on the client-side and back, the data gets reset to the first page, but the `pageInfo` doesn't get reset.

**Expected behavior:**
Because the data gets reset, the pageInfo should be reset too.

Checking if it's related to the cache policy or not. Reproduces with either `CacheOrNetwork` and `CacheAndNetwork` - did not test other caching policies.

What is the intended behavior; should it retain the data list when navigating back to the page and when the policy is set to cache first or reset the data and pageInfo?

### Severity

annoyance

### Steps to Reproduce the Bug

See above.

**Comment by AlecAivazis** [comment] 2022-12-28 05:03
So the expected behavior is that the cache will hold onto what it knows. If you have loaded information for the next page, the cache should remember that and the `pageInfo` value should reflect the full list. 

> the data gets reset to the first page

This seems like the bug. What seems strange is that the `pageInfo` value is compute off of the current list but maybe that's not happening?

**Comment by AlecAivazis** [comment] 2023-01-04 09:20
I'm unable to reproduce this in the e2e test suite for cursor-based pagination in queries or fragments. I'm going to close this but feel free to let me know if things aren't behaving like I described and we can open it back up

**Closed by AlecAivazis** 2023-01-04 09:21 UTC
Labels: Still investigating
