### ISSUE TITLE
Typescript "failing" in houdinigraphql.com exemple?

### ISSUE THREAD

**Issue by tofsjonas** [HoudiniGraphql/houdini#1042] opened 2023-04-06 07:43 UTC
### Describe the bug

(Not sure if this is a bug or a feature request, but here goes)

When using the code in the example I am not getting any types.

<img width="545" alt="actual" src="https://user-images.githubusercontent.com/1842179/230307520-b6ce46fe-4a7c-43a2-b5df-e1424f6a9a9f.png">

I would expect something more like this:

<img width="545" alt="expected" src="https://user-images.githubusercontent.com/1842179/230307550-8602f191-25ac-4bab-9101-9f5aa2efc349.png">

but without having to manually set `as ExampleQuery$result`

### Severity

annoyance

### Steps to Reproduce the Bug

Download <https://stackblitz.com/edit/vitejs-vite-gecm9u/> and install. The reproduction link is not very helpful, since there are no tooltips there

### Reproduction

https://stackblitz.com/edit/vitejs-vite-gecm9u?file=src/Example.svelte

**Comment by AlecAivazis** [comment] 2023-04-06 17:21
Hm, that's verry strange. 

I'm assuming you ran the dev server at least once when testing without the explicit type? If I look at the reproduction link there is an overloaded definition for the `graphql` function at `$houdini/runtime/index.d.ts`. You _should_ see a line for every query in your document that maps it to the correct type.  Are you seeing the same thing?

**Comment by tofsjonas** [comment] 2023-04-06 18:22
Yes, they're there.

Could it be a vscode thing? Some setting that got messed up? 🤞

**Comment by tofsjonas** [comment] 2023-04-06 18:48
Then again, `allItems` looks correct..

![allitems](https://user-images.githubusercontent.com/1842179/230468153-bf52b823-53f0-40fa-9ce7-f1d71dc48909.png)

**Comment by AlecAivazis** [comment] 2023-04-16 19:39
@tofsjonas were you able to figure this out? if not, mind putting a reproduction together so I can take a look?

**Comment by tofsjonas** [comment] 2023-04-17 09:38
Nope 😢

**Comment by AlecAivazis** [comment] 2023-04-29 04:59
Hm well if you want to connect on discord I'm more than happy to debug this. I'm going to close this issue since there's nothing really actionable here just yet. Happy to open another one we understand what's going on

**Closed by AlecAivazis** 2023-04-29 04:59 UTC
Labels: Still investigating
