### ISSUE TITLE
Having a +layout.server.ts file makes the client session undefined

### ISSUE THREAD

**Issue by saveliy-kremen** [HoudiniGraphql/houdini#1106] opened 2023-06-14 14:30 UTC
### Describe the bug

Having a +layout.server.ts file  in routes, even if it's empty, makes the client session undefined from this:

// file - client.ts

```
import { HoudiniClient } from '$houdini';
import { PUBLIC_GRAFBASE_API_URL } from '$env/static/public';

export default new HoudiniClient({
    url: PUBLIC_GRAFBASE_API_URL,
    fetchParams({ session }) {
        console.log("session", session)
        return {
            headers: {
                Authentication: `Bearer ${session?.authToken}`,
            },
        }
        return {}
    },
})
```

### Severity

annoyance

### Steps to Reproduce the Bug

Put file  +layout.server.ts file  in routes

**Comment by mcavaciocchi** [comment] 2023-07-19 12:10
Having the same problem.. :(

**Comment by mcavaciocchi** [comment] 2023-07-19 16:07
@saveliy-kremen 

Maybe it helps you.
https://discord.com/channels/1024421016405016718/1131236758890233977

**Comment by saveliy-kremen** [comment] 2023-07-20 05:58
I tried this solution. But in my case it doesn't matter what is in this file. Message "debug" not  displayed.

`export const load: LayoutServerLoad = async (event) => {

    console.log("debug") 

     return {   
        session: event.locals.session  
    }

}`

**Comment by saveliy-kremen** [comment] 2023-07-20 06:52
I tried this solution. The session appears in PageData. 
But it still disappears in client.ts. As far as I understand, +layout.server.ts overwrites the session that hooks.server.ts sets.
It would be nice to supplement the documentation on how to proceed in this case.

**Comment by AlecAivazis** [comment] 2024-07-07 08:30
I'm not able to reproduce this in the project's e2e tests. I'm going to close this since it doesn't seem to be wide spready but If you have the time to put together a reproduction, i'd gladly take a closer look

**Closed by AlecAivazis** 2024-07-07 08:30 UTC

**Comment by crankyDino** [comment] 2024-09-16 21:22
I'm also having the same issue. It may not be very widespread but it does seem like a real/major issue

**Comment by AlecAivazis** [comment] 2024-09-16 23:10
If you have the time to put together a reproduction using this project's e2e tests it would go a long way to helping me debug the issue. I unforunately wasn't able to reproduce it when I tried
