### ISSUE TITLE
adapter-node build fail with  Unexpected character  error

### ISSUE THREAD

**Issue by xmlking** [HoudiniGraphql/houdini#780] opened 2022-12-20 04:33 UTC
### Describe the bug

after adding *houdini* to the minimal SvelteKit project, `adapter-node ` start failing.
before adding houdini config, build is working fine. 

```
npm run build:node

> svelte-starter-kit@0.0.1 build:node
> cross-env ADAPTER=node npm run build


> svelte-starter-kit@0.0.1 build
> vite build


vite v4.0.2 building for production...
🎩 Generating runtime...
📃 Unchanged: 8
transforming (1) node_modules/@sveltejs/kit/src/runtime/client/start.js8:12:59 PM [vite-plugin-svelte] /src/routes/+page.svelte:3:3 A11y: '#' is not a valid href attribute
1: <script></script><h1>Welcome to SvelteKit</h1>
2: <p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
3: <a href="#" class="btn-primary btn">btn</a>
      ^
4: 
transforming (51) node_modules/devalue/src/utils.js
🌼 daisyUI components 2.45.0  https://daisyui.com
  ✔︎ Including:  base, components, 29 themes, utilities
  ❤︎ Support daisyUI:  https://opencollective.com/daisyui 
  
✓ 144 modules transformed.
8:13:01 PM [vite-plugin-svelte] dom compile done.
package                 files     time     avg
svelte-starter-kit          3   35.1ms  11.7ms
@sveltejs/kit               1   21.0ms  21.0ms
[commonjs--resolver] Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
file: /Users/schintha/Developer/Work/SPA/aaa/svelte-starter-kit/node_modules/fsevents/fsevents.js:1:0
1: ����@�
         @�������(__TEXT��__text__TEXTF3F�__stubs__TEXT4e 4�__stub_helper__TEXTTf�Tf�__const__TEXTHHh__cstring__TEXTPh%Ph__unwind_info__TEXTx�x(__DATA�@�@__nl_symbol_ptr__DATA�0__got__DAT�1__la_symbol_ptr__DATA �� �4__mod_init_func__DATA���    __const__DATA��P��__data__DATA��H��H__LINKEDIT�@�<"�0�����H�����h
                                                                                 P���3�d�A�1�>ۂ�2BEU`�$
   ^
2: 
3: 
   *
    h���/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
                                                                                     h
                                                                                      b/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
                                                                                                                                                                0�/usr/lib/libc++.1.dylib
                                                                                                                                                                                         8<
                                                                                                                                                                                           /usr/lib/libSystem.B.dylib&@�h)��UH��]�f.�UH��]�f.�UH��]�f.�UH��SPH��H�~H�H�;1���H���H��H�[]�=f.�UH��AVSH��PI����I�FHH�5;H�U��
error during build:
RollupError: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
    at error (file:///Users/schintha/Developer/Work/SPA/aaa/svelte-starter-kit/node_modules/rollup/dist/es/shared/rollup.js:2001:30)
    at Module.error (file:///Users/schintha/Developer/Work/SPA/aaa/svelte-starter-kit/node_modules/rollup/dist/es/shared/rollup.js:12982:16)
    at Module.tryParse (file:///Users/schintha/Developer/Work/SPA/aaa/svelte-starter-kit/node_modules/rollup/dist/es/shared/rollup.js:13359:25)
    at Module.setSource (file:///Users/schintha/Developer/Work/SPA/aaa/svelte-starter-kit/node_modules/rollup/dist/es/shared/rollup.js:13268:24)
    at ModuleLoader.addModuleSource (file:///Users/schintha/Developer/Work/SPA/aaa/svelte-starter-kit/node_modules/rollup/dist/es/shared/rollup.js:22700:20)
```

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

minimal code to reproduce issue 
```
git clone  https://github.com/xmlking/sveltekit-houdini-issue.git
npm install
npm run build:node
```

### Reproduction

https://github.com/xmlking/sveltekit-houdini-issue.git

**Comment by xmlking** [comment] 2022-12-20 04:42
to test, remove `houdini()` plugin in `vite.config.ts`

i.e., `plugins: [houdini(), sveltekit()]` --> 	`plugins: [ sveltekit()]`

then run:
```shell
npm run build:node
```

Output : build works without errors
```
> svelte-starter-kit@0.0.1 build:node
> cross-env ADAPTER=node npm run build


> svelte-starter-kit@0.0.1 build
> vite build


vite v4.0.2 building for production...
transforming (1) node_modules/@sveltejs/kit/src/runtime/client/start.js8:41:01 PM [vite-plugin-svelte] /src/routes/+page.svelte:3:3 A11y: '#' is not a valid href attribute
1: <h1>Welcome to SvelteKit</h1>
2: <p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
3: <a href="#" class="btn-primary btn">btn</a>
      ^
4: 
transforming (37) node_modules/devalue/src/constants.js
🌼 daisyUI components 2.45.0  https://daisyui.com
  ✔︎ Including:  base, components, 29 themes, utilities
  ❤︎ Support daisyUI:  https://opencollective.com/daisyui 
  
✓ 39 modules transformed.
8:41:01 PM [vite-plugin-svelte] dom compile done.
package                 files     time     avg
svelte-starter-kit          3   37.1ms  12.4ms
@sveltejs/kit               1   22.4ms  22.4ms

vite v4.0.2 building SSR bundle for production...
transforming (1) .svelte-kit/build/index.js8:41:02 PM [vite-plugin-svelte] /src/routes/+page.svelte:3:3 A11y: '#' is not a valid href attribute
1: <h1>Welcome to SvelteKit</h1>
2: <p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
3: <a href="#" class="btn-primary btn">btn</a>
      ^
4: 
✓ 47 modules transformed.
8:41:02 PM [vite-plugin-svelte] ssr compile done.
package                 files    time     avg
svelte-starter-kit          4   8.8ms   2.2ms
Generated an empty chunk: "hooks".
.svelte-kit/output/server/vite-manifest.json                  1.13 kB
.svelte-kit/output/server/chunks/hooks.js                     0.00 kB
.svelte-kit/output/server/entries/pages/_layout.svelte.js     0.25 kB
.svelte-kit/output/server/entries/pages/_page.svelte.js       0.37 kB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js   0.79 kB
.svelte-kit/output/server/chunks/index.js                     3.22 kB
.svelte-kit/output/server/index.js                           78.69 kB

Run npm run preview to preview your production build locally.
.svelte-kit/output/client/_app/version.json                                            0.03 kB
.svelte-kit/output/client/vite-manifest.json                                           2.36 kB
.svelte-kit/output/client/_app/immutable/assets/_layout-2ecff240.css                  33.49 kB │ gzip:  6.70 kB
.svelte-kit/output/client/_app/immutable/chunks/1-eb604b7f.js                          0.09 kB │ gzip:  0.10 kB
.svelte-kit/output/client/_app/immutable/chunks/2-014bf943.js                          0.10 kB │ gzip:  0.10 kB
.svelte-kit/output/client/_app/immutable/chunks/0-89ead9ea.js                          0.10 kB │ gzip:  0.10 kB
.svelte-kit/output/client/_app/immutable/components/pages/_layout.svelte-b8d1d550.js   0.55 kB │ gzip:  0.36 kB
.svelte-kit/output/client/_app/immutable/components/error.svelte-03b3ffcb.js           0.98 kB │ gzip:  0.57 kB
.svelte-kit/output/client/_app/immutable/components/pages/_page.svelte-781349e5.js     1.02 kB │ gzip:  0.56 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons-c1916556.js                 2.58 kB │ gzip:  1.34 kB
.svelte-kit/output/client/_app/immutable/chunks/index-7f3551f2.js                      6.87 kB │ gzip:  2.79 kB
.svelte-kit/output/client/_app/immutable/start-ad854b67.js                            26.46 kB │ gzip: 10.36 kB

> Using @sveltejs/adapter-node
Generated an empty chunk: "hooks".
  ✔ done

```

**Comment by AlecAivazis** [comment] 2022-12-20 04:57
Thanks for reporting this @xmlking! I'll take a look and let you know what i find

**Comment by AlecAivazis** [comment] 2022-12-20 05:30
I'm pretty sure the issue is related to the `houdini` plugin since the generated runtime imports your config file which causes vite to bundle the `vite` module with the rest of your client. This clearly isn't an intended use case for vite so it's not totally surprising its not working.

**Comment by xmlking** [comment] 2022-12-20 07:13
May be we can try exclude vite in `optimizeDeps` at
https://github.com/xmlking/sveltekit-houdini-issue/blob/main/vite.config.ts#L51
I am away from computer, will try when I get back

**Comment by xmlking** [comment] 2022-12-20 07:22
May be we should explore using   [$env/dynamic/public](https://kit.svelte.dev/docs/modules#$env-dynamic-public) for houdini.config.js as well🤔

**Comment by AlecAivazis** [comment] 2022-12-20 07:25
The PR i linked to will load the appropriate files for you to refer to however you want. The actual  `$env` alias won't work without a lot of effort since it's an alias that the kit plugin generates behind the scenes which means we'd have to run `vite` as part of the codegen process.

**Comment by AlecAivazis** [comment] 2022-12-20 09:37
Closing this since it should be fixed in `0.19.0`. let me know if the problem still persists and we can open it back up. Thanks for being patient!

**Closed by AlecAivazis** 2022-12-20 09:37 UTC

**Comment by xmlking** [comment] 2022-12-20 18:54
thanks a lot, @AlecAivazis  I upgraded to `0.19.0` and all works fine now.

latest working code: https://github.com/xmlking/sveltekit-houdini-issue

**Comment by AlecAivazis** [comment] 2022-12-20 18:58
Great to hear! Btw I don't think the default marshalers you defined are necessary - iirc, what you have there _is_ is the default value

**Comment by xmlking** [comment] 2022-12-21 05:33
Do you mean  I don’t have to provide DateTime, Decimal and URL ?
I recall it was giving  warning logs  for hstore, jsonb etc.
