### ISSUE TITLE
types generated for fragment is wrong. 

### ISSUE THREAD

**Issue by xmlking** [HoudiniGraphql/houdini#737] opened 2022-12-02 22:16 UTC
### Describe the bug

I am using `fragment` in my query as shown below, I was hoping the type generated will have fields specified in the  fragment but actually it has only `$fragments`  field. 

```
query ListPolicies($limit: Int = 50, $offset: Int = 0, $orderBy: [tz_policies_order_by!] = [{ update_time: desc_nulls_last }]) {
	tz_policies(order_by: $orderBy, limit: $limit, offset: $offset, where: { delete_time: { _is_null: true } }) {
		...Policy_list_fields
	}
}

fragment Policy_list_fields on tz_policies {
	id
	action
	annotations
	app_id
}
```

<img width="875" alt="image" src="https://user-images.githubusercontent.com/627951/205398075-7dfbfec5-d857-4502-b2f0-a7bce26e4838.png">
<img width="846" alt="image" src="https://user-images.githubusercontent.com/627951/205398130-e7d13355-f0a2-4aa4-ad88-e8d57c48ec8b.png">

<img width="875" alt="image" src="https://user-images.githubusercontent.com/627951/205398587-582b493e-5485-4e3d-9c0f-5af9f1300786.png">

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

git clone https://xmlking@github.com/xmlking/svelte-starter-kit.git
npm install
npm run dev

open repo in `VS Code` and  check the types in  for `policies1` in `svelte-starter-kit/src/routes/(app)/dashboard/policies/+page.server.ts` `id` us shown as error type. 

access the URL, which should print the `ID, Count` to console. 

http://localhost:5173/dashboard/policies

### Reproduction

https://xmlking@github.com/xmlking/svelte-starter-kit.git

**Comment by AlecAivazis** [comment] 2022-12-02 22:22
Hey @xmlking - thanks for opening this issue.

I know it's a big surprising but this is actually an intended behavior. By default, houdini tries to protect you against coupling components together in coincidental ways by hiding fields that you did not explicitly ask for. In my experience, when 2 views ask for the same data but have different structure, the duplicate selection is more of a coincidence than a logical coupling and probably shouldn't be extracted into a fragment. If you were to change that fragment, you have to go hunt down every query that uses it and make sure that their components didn't rely on the old data. Typescript does make this easier to do but imo its indicative of a leaky abstraction. If there are 2 views that have the same data requirement and the same structure, then that's a perfect situation for a fragment, imo. 

It might help to have a concrete example so let's consider a UserAvatar component that takes in a user and renders their profile picture. If you had a view that rendered a UserAvatar, the query that requests that user might also want to know the user's first name for their own view. In that scenario, the route with the query should explicitly ask for the first name and not rely on the coincidence that UserAvatar also wants the first name. The reason for this is that if UserAvatar no longer wants the first name, now you have to go update the query: the route is tightly coupled to an implementation detail of another component. By having masking turned on by default, houdini is encouraging you to minimize this so your views don't break in unexpected ways.

All of that being said, there are some situations where a fragment shouldn't be masked and for those situations, houdini lets you turn off masking on a specific fragment with the @houdini(mask: false) directive. You can also turn off masking globally with the disableMasking config value but I highly recommend leaving that on unless you are migrating to houdini in a project that wasn't built with this in mind.

**Comment by AlecAivazis** [comment] 2022-12-03 03:48
I'm closing this to keep things tidy - let me know if you run into any more questions and I can reopen if necessary

**Closed** 2022-12-03 03:48 UTC

**Comment by fuwaneko** [comment] 2022-12-10 18:01
@AlecAivazis I have a similar issue, so I'm going to ask here instead of opening a new one.

Let's say I have this component:
```svelte
<script lang="ts">
	import type { ProjectInfo } from '$houdini'
	import Project from '$lib/Project.svelte'

	export let projects: ProjectInfo[] = []
	export let pinned: boolean = false
</script>

<ul class="ml-2">
	{#each projects as project}
		{#if project.isPinned == pinned}
			<li><Project {project} /></li>
		{/if}
	{/each}
</ul>
```

Which works with this query on the upper level (SvelteKit page with loader) and fragment in Project component:
```graphql
query Projects {
  projects {
    ...ProjectInfo
  }
}

fragment ProjectInfo on Project {
  id
  title
  isPinned
}
```

How do I avoid Typescript complaining about "isPinned" not existing on ProjectInfo? Or, generally speaking, how to pass typed fragment data around components, filter, map, perform transformations on it? It works in runtime but Typescript complains. Unmasking doesn't help. I pretty much expected the same as op: ProjectInfo type to contain all fields from the fragment.

If I change type to this:
```typescript
export let projects: (ProjectInfo & ProjectInfo$data)[] = []
```
Typescript does not complain anymore neither in the component, nor on the upper level. Is this the recommended approach?

My use case is pretty much [described here](https://www.apollographql.com/blog/graphql/fragments/using-graphql-fragments-for-safer-cleaner-and-faster-code/). That's why I expected similar behavior.

**Comment by jycouet** [comment] 2022-12-10 18:56
> Unmasking doesn't help

What do you mean? Do you have an error? Did you spot a bug to fix?

---

To work with fragments, it's generally better to use the `fragment` feature of Houdini.
- You can find the doc here: https://www.houdinigraphql.com/api/fragments
- In typescript, you can find a snippet at the bottom of: https://www.houdinigraphql.com/guides/typescript#Fragments

Let us know if the doc is useful/sufficient/clear, or not. The idea is to improve 👍
Do you have the code somewhere so that I can send a PR to show you an example?
